import Head from 'next/head'
import { Inter } from '@next/font/google'
import MainArea from '../components/MainArea'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const { data: session, status } = useSession({
    onUnauthenticated() {
      router.push('/auth/login')
    }
  })



  return (
    <>
      <Head>
        <title>Dashboard - Muzique</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>


        <main>
          <MainArea />
        </main>
    </>
  );
}
